---
# Worker Cluster Configuration for MultiKueue
# This file contains all the necessary manifests for the worker cluster
apiVersion: v1
kind: Namespace
metadata:
  name: multikueue-demo
---
# ResourceFlavor for CPU resources
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-cpu
  namespace: kueue-system
spec: {}
---
# ResourceFlavor for Memory resources
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-memory
  namespace: kueue-system
spec: {}
---
# ClusterQueue for the worker cluster
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: worker-cluster-queue
  namespace: kueue-system
spec:
  namespaceSelector: {}  # Match all namespaces
  resourceGroups:
    - coveredResources: ["cpu"]
      flavors:
        - name: default-cpu
          resources:
            - name: "cpu"
              nominalQuota: 4  # 4 CPU cores available
    - coveredResources: ["memory"]
      flavors:
        - name: default-memory
          resources:
            - name: "memory"
              nominalQuota: 8Gi  # 8GB memory available
  queueingStrategy: BestEffortFIFO
  preemption:
    withinClusterQueue: LowerPriority
    reclaimWithinCohort: Any
---
# LocalQueue for the multikueue-demo namespace (must match manager cluster)
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: manager-local-queue
  namespace: multikueue-demo
spec:
  clusterQueue: worker-cluster-queue
---
# Default LocalQueue for default namespace (must match manager cluster)
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: default-local-queue
  namespace: default
spec:
  clusterQueue: worker-cluster-queue
---
# Sample Pod for testing worker cluster functionality
apiVersion: v1
kind: Pod
metadata:
  name: worker-test-pod
  namespace: multikueue-demo
  labels:
    kueue.x-k8s.io/queue-name: worker-local-queue
spec:
  containers:
    - name: test-container
      image: busybox:latest
      command: ["sh", "-c", "echo 'Worker cluster is ready!'; sleep 30"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  restartPolicy: Never
