---
# Remote Cluster Configuration for MultiKueue
# This file contains all the necessary manifests for the remote cluster
apiVersion: v1
kind: Namespace
metadata:
  name: multikueue-demo
---
# ResourceFlavor for CPU resources
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-cpu
  namespace: kueue-system
spec: {}
---
# ResourceFlavor for Memory resources
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-memory
  namespace: kueue-system
spec: {}
---
# ClusterQueue for the remote cluster
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: remote-cluster-queue
  namespace: kueue-system
spec:
  namespaceSelector: {}  # Match all namespaces
  resourceGroups:
    - coveredResources: ["cpu"]
      flavors:
        - name: default-cpu
          resources:
            - name: "cpu"
              nominalQuota: 4  # 4 CPU cores available
    - coveredResources: ["memory"]
      flavors:
        - name: default-memory
          resources:
            - name: "memory"
              nominalQuota: 8Gi  # 8GB memory available
  queueingStrategy: BestEffortFIFO
  preemption:
    withinClusterQueue: LowerPriority
    reclaimWithinCohort: Any
---
# LocalQueue for the multikueue-demo namespace (must match manager cluster)
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: remote-queue
  namespace: multikueue-demo
spec:
  clusterQueue: remote-cluster-queue
---
# Default LocalQueue for default namespace
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: default-local-queue
  namespace: default
spec:
  clusterQueue: remote-cluster-queue
