name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        check-type:
          - shellcheck
          - yamllint
          - markdownlint
          - gitignore
          - file_structure
          - script_permissions
          - yaml_dry_run
          - documentation
          - script_consistency

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
          sudo npm install -g markdownlint-cli2

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Run ${{ matrix.check-type }} check
        run: ./run-tests.sh ${{ matrix.check-type }}
